### PR TITLE
Pg scaling demo

### PR DESCRIPTION
**Pull request by lukekarrys**
- [x] Line graph is not properly clipping the right edge in chrome
- [x] Jobs in queue count width for large numbers (eg 1.1k)
- [x] Make charts extend to height of window
- [x] Fix safari layout issues
- [x] Review layout of other pages with new index layout changes
- [x] Stream graph sometimes isn't visible
- [x] hovering over hamburger nav makes a horizontal scrollbar appear. It might be related to the overflow from the chart below it, but changing the `right` value to 10 fixes it. 
- [x] /audience's and /booth's titles are chillin on the left now (prob shared styling with the one on the root)
- [x] /audience's and /booth's graph is shifted to the left

### CODE REVIEW

**Comment by lukekarrys** [comment]
@crcastle I think I might need a different level of github permissions in order to see the security alerts page for this repo? The link above returns a 404 for me.

**Comment by lukekarrys** [comment]
@crcastle On the machine that is having rendering issues, can you check this url as well and see how it performs? https://thawing-gorge-71058.herokuapp.com I've seen that issue once before but it was related to bad data coming from the server. I haven't been able to reproduce any issues on the client yet.

**Comment by crcastle** [comment]
@lukekarrys Unfortunately I don't have that machine with me now. It is somewhere enroute between Florida (Postgres Open Conf) and New York (Strata Data Conf). I'll ask the person in charge of coordinating it if either 1) they have the same machine type in the office they can test on and 2) if the person coordinating the shipping can get access to this machine to test soon. Worst case scenario is that we test on the evening of Tuesday the 24th when we'll be setting up for Strata in New York.

**Comment by crcastle** [comment]
@lukekarrys regarding resolving the security vulnerabilities, I increased your permissions level on this repo to "Admin". Let me know if you still can't see this link: https://github.com/heroku-examples/analytics-with-kafka-redshift-metabase/network/alerts

image

**Comment by lukekarrys** [comment]
I think I updated all the deps related to the security alerts, but they wont show as resolved in GitHub until this is merged to master.

**Comment by crcastle** [comment]
Regarding vuln resolution, thanks @lukekarrys! Let's merge this branch to master once this checklist[https://github.com/heroku-examples/analytics-with-kafka-redshift-metabase/pull/9#pullrequestreview-287785999](https://github.com/heroku-examples/analytics-with-kafka-redshift-metabase/pull/9#pullrequestreview-287785999) is done.

Also can you cherry pick the commits or make the same updates to the `pg-scaling-demo-async` branch? Or maybe it'll be easier to just blow away that branch, re-fork it from this one after you are done with all the checklist updates, and then make the one-line async/sync change in it.

**Pull request merged**
